 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>bundleUUID</key>
	<string>E1E14662-0C3F-4423-866F-3D35BA780DD9</string>
	<key>name</key>
	<string>GTA3Script</string>
	<key>scopeName</key>
	<string>source.gta3script</string>
	<key>fileTypes</key>
	<array>
		<string>sc</string>
	</array>
    <key>patterns</key>
    <array>
        <dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.gta3script</string>
        </dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.gta3script</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.gta3script</string>
		</dict>
        <dict>
            <key>match</key>
            <string>\b((0x[0-9A-Fa-f\-]+)|([0-9\-]+)|([0-9\.fF]+))\b</string>
            <key>name</key>
            <string>constant.numeric.gta3script</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*\S+:</string>
            <key>name</key>
            <string>entity.name.function</string>
        </dict>
        <dict>
            <key>match</key>
             <string>(?i:^\s*\bL?VAR_(INT|FLOAT|TEXT_LABEL|TEXT_LABEL16)\b)</string>
            <key>name</key>
            <string>storage.type.gta3script</string>
        </dict>
        <dict>
            <key>match</key>
             <string>(?i:^\s*\b(MISSION_START|MISSION_END|SCRIPT_START|SCRIPT_END)\b)</string>
            <key>name</key>
            <string>keyword.control.gta3script</string>
        </dict>
        <dict>
            <key>match</key>
             <string>(?i:^\s*\b(ELSE|ENDIF|ENDWHILE|REPEAT|ENDREPEAT|SWITCH|CASE|DEFAULT|BREAK|ENDSWITCH)\b)</string>
            <key>name</key>
            <string>keyword.other.contro.gta3script</string>
        </dict>
        <dict>
            <!-- Matched when e.g. WHILE is alone in a line -->
            <key>match</key>
             <string>(?i:^\s*\b(WHILE|WHILENOT|IF|IFNOT)\b\s*$)</string>
            <key>name</key>
            <string>keyword.other.contro.gta3script</string>
        </dict>
        <dict>
            <!-- Matched when e.g. AND is alone in a line -->
            <key>match</key>
             <string>(?i:^\s*\b(NOT|AND|OR)\b\s*$)</string>
            <key>name</key>
            <string>keyword.other.operato.andornot.gta3script</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*(?i:((?:IF\s+)|(?:WHILE\s+))?((?:AND\s+)|(?:OR\s+))?(NOT\s+)?)([0-9A-Z_]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.contro.gta3script</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.operato.andornot.gta3script</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.operato.andornot.gta3script</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.command.gta3script</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
             <string>\b[A-Z]\S*\b</string>
            <key>name</key>
            <string>constant.language.gta3script</string>
        </dict>
    </array>
</dict>